name = mcl_bows
author = Arcelmi
description = This mod adds bows and arrows for Betacraft.
depends = controls, mcl_enchanting, mcl_init, mcl_util, mcl_shields, mcl_player, playerphysics, doc, doc_identifier
