name = mcl_eating
description = Allows players to eat food items. Food restores health instead of hunger.
depends = mcl_util, mcl_player, mcl_damage, mcl_serverplayer, controls, playerphysics, mcl_shields
